### PR TITLE
Calendar documentation

### LINKED ISSUE #9: Calendar is undocumented
curl --user testuser:testpassword -H "Content-application/json" -X GET api.ijzersterkdelft.nl/calendar/
"{\"status\":\"200 OK\",\"details\":\"calendar returned\",\"result\":[\"1\",\"2\"]}"

curl --user testuser:testpassword -H "Content-application/json" -X GET api.ijzersterkdelft.nl/calendar/1
"{\"status\":\"200 OK\",\"details\":\"calendarEvent returned\",\"result\":{\"id\":\"1\",\"title\":\"Birth of the calendar\",\"description\":\"This event hallmarks the birth of the first calendarEvent\",\"start\":{\"date\":\"2015-08-03 18:30:00.000000\",\"timezone_type\":3,\"timezone\":\"Europe\\/Amsterdam\"},\"end\":{\"date\":\"2015-08-03 19:00:00.000000\",\"timezone_type\":3,\"timezone\":\"Europe\\/Amsterdam\"},\"viewlevel\":\"0\",\"editlevel\":\"2\"}}"

Dit nog documenteren. Nu even hier voor @Pouja

### PR DESCRIPTION
**Pull request by danielcolon**
Referring to your comment on #9
##### 1. Fist we have to know what "events" are in our domain. With that we can specify which type of events we can expect.

_We can use the title for now. I suggest we can add a loose eventType stored in a different table and associate it by id._
##### 2. Will all events be time constricted, or will they be day constricted.

_Use of ISO-8601 ensures we cover all options_
##### 3. Do we even want that people can comment on events? Also will the comments be CRUD then?

_Not yet. But it can easily be implemented_
##### 4. Does a person comment that he wants to participate? Or will there be a "i will be there" button?

_There will be an I will be there system. Questions or remarks going with the description can either be done in a comment system if we build one or a smarter version where you can select stuff like exercises you want to do._
##### 5. Can an event also have a static html page? Or will we just display some small information under it?

_The event description can be 512 characters long and can be html as far as I'm concerned. If you need more space I think it's best we refer to a blog or newspost on the site since it'll probably be an important event then_

Please review @Pouja 
Fixes #9

### CODE REVIEW

**Comment by Pouja** [comment]
> We can use the title for now. I suggest we can add a loose eventType stored in a different table and associate it by id.

We need this as well for the basic calendar events. Since we are using colors in the view to describe different types of events.

The rest of it, I agree 100% with it:+1:

**Comment by Pouja** [comment]
Btw I assume that the viewlevel is the maximum of what the current user which requests it can see?
So if there are no credentials passed in the header then only the calendar events with viewlevel = 0 are returned right, and if it is a normal user only calendar events with viewlevel = 1.

Also what is the function of the editlevel. Is there a case where the editlevel and the viewlevel differ. Admins should be able to CRUD all events. And normal users only their own events, right?

**Comment by Pouja** [comment]
Forgot to mention, there is also a need for searching for events. For example searching for all events that occur between date A and date B.

**Comment by danielcolon** [comment]
@Pouja kan jij pull request bekijken en eventueel mergen?

**Comment by danielcolon** [comment]
I'm gonna merge so everything is nice and consolidated. You can check it out later.
Closes #9

**Pull request merged**
